### ISSUE TITLE
DimThread crashing my server

### ISSUE THREAD

**Issue by BootSwitch** [WearBlackAllDay/DimensionalThreading#21]
When I have DimThread installed, my server crashes (not instantly).
[crash-2021-04-15_19.58.06-server.txt](https://github.com/WearBlackAllDay/DimensionalThreading/files/6324086/crash-2021-04-15_19.58.06-server.txt)

**Comment by TelepathicGrunt** [comment]
A similar crash is occurring in my World Blender dimension if Dimensional Threads and StarLight is on. It is during entity ticking like the minecraft:enderman in the log above but not caused by Lithium this time. 

Here's the crash from the latest.log that was reported to me
https://paste.ee/p/7PQ0o

Here's my ticking code for my entity
https://github.com/TelepathicGrunt/WorldBlender-Fabric/blob/35e2237f7657487b8c38ae649f79d5e7a513397e/src/main/java/com/telepathicgrunt/worldblender/entities/ItemClearingEntity.java#L60-L126

I'm wondering if it because I am removing a ton of blocks when my entity tick at first. And that change of blocks causes StarLight to try and recalculate lighting for the area and then crashes due to DimensionalThreading. 

It could be that Lithium and Starlight are using code that isn't meant to be multi-threaded and the result is these crashes during entity ticking

**Comment by WearBlackAllDay** [comment]
@BootSwitch your crash is directly linked to Lithium, you should probably update your outdated (0.6.3) version to the newest release.

@TelepathicGrunt your crash is probably(pretty sure) linked to starlight, the exact cause requires further investigation.
