### ISSUE TITLE
ticking world error

### ISSUE THREAD

**Issue by Monster-Zer0** [WearBlackAllDay/DimensionalThreading#23]
server crashes multiple times in row with this error https://paste.alloffabric.com/quxoteyibu.yaml

not sure if it's a dimthread thing or not, but any help would be appreciated.

**Comment by WearBlackAllDay** [comment]
this crash is not linked to dimthread.

you are running an excessive amount of mods and i cannot read thru all of their sources (over 7k due to mixins before World#getChunk), but i can rule out dimthread as a cause.
I suggest narrowing down/binary searching the mod(combination?) in question from a fresh server this to get a clean stacktrace, then work off that
