### ISSUE TITLE
Repeated Crashing

### ISSUE THREAD

**Issue by pooky125** [WearBlackAllDay/DimensionalThreading#28]
Hi, me again. Tried yesterdays update, and while the gamerules are now populating, I'm continuing to get crashes. Server is hosted on a single core of a 3700x with 16 gigs of ram. I have these mods installed:

BlueMap-1.53.0-1.17.jar
fabric-api-0.34.10_+1.17.jar
Fabric-Discord-Link-0.9.4.jar
fdlink-api-0.1.0.jar
lithium-fabric-mc1.17-0.7.0.jar
starlight-fabric-1.0.0-RC2-1.17.x.jar

I tried running it in singleplayer as well, without starlight in one test, and with nothing but dimthread in the other test, in both cases, it didn't seem to crash, but it also wasn't advancing time when I was in bed in a custom dimension. Admittedly, I didn't have either test open long enough to see if it WOULD crash,  as it takes 2-3 minutes from launch before it poops itself and reboots. I've included a copy of my crash log for you. 

[crash-2021-06-12_19.46.55-server.txt](https://github.com/WearBlackAllDay/DimensionalThreading/files/6646244/crash-2021-06-12_19.46.55-server.txt)

**Comment by WearBlackAllDay** [comment]
very similarily to #24, this is not actually dimthreads issue.
whenever something with dimthread installed crashes, you are going to read lines about threads, which makes it easy to associate with dimthread. This is NOT however because dimthread itself, but something it ran on the threads it creates (which is what this mod does after all) crashed.
If you can narrow down the exact combination of mods that is causing the (potential) incompatibility, i might be able to provide more help.
